import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
import { Footer } from "@/components/layout/Footer";
import { Navbar } from "@/components/layout/navbar/Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// Configuración de la metadata de la aplicación
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout principal de la aplicación
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased bg-slate-50`}>
        <SessionProvider>
          <Navbar />
          {children}

          <Footer />
        </SessionProvider>

        <Toaster />
      </body>
    </html>
  );
}
